version: '3.8'
services:
  portfolio_api:
    build: ./backend
    container_name: portfolio_api_c
    ports:
      - '5555:5555'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=5555
      - MONGODB_URL=mongodb+srv://kurnlhector:Jagdtiger@cluster0.se2oxkf.mongodb.net/portfolio?retryWrites=true&w=majority

  portfolio_frontend: 
    build: ./frontend
    container_name: portfolio_frontend_c
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true